#!/usr/bin/env bash

source $(dirname "$0")/termination-env > /dev/null

thrsh=${PRE_STOP_HANDLER_RND_THRESHOLD-98}

while true; do
  rnd=$(( $RANDOM % 100 ))
  sleep="${PRE_STOP_HANDLER_SLEEP:-$(( $heartbeat_threshold + ($RANDOM % 2) * ($RANDOM % 2) * ($RANDOM % 2) ))}"
  printf "%s: will sleep %ss if %s -ge %s\n" \
    "$FOO" \
    "$sleep" \
    "$thrsh" \
    "$rnd"
  if [[ $rnd -lt $thrsh ]]; then
    sleep $sleep
  else
    # exit 116
    break
  fi
done
