#!/usr/bin/env bash

source $(dirname "$0")/termination-env > /dev/null

while true; do
  rnd=$(( $RANDOM % 100 ))
  printf "${FOO}: pretend doing something #%s\n" \
    "$rnd"
  if [[ $rnd -lt 98 ]]; then
    sleep "${PRE_STOP_HANDLER_SLEEP:-$(( $recheck_sleep + $recheck_sleep * ($RANDOM % 2) * 2 ))}"
  else
    # exit 116
    break
  fi
done
